import Head from "next/head";
import styles from "@component/styles/Home.module.css";
import { FcGoogle } from "react-icons/fc";
import { GiNotebook } from "react-icons/gi";
import { useEffect, useRef, useState } from "react";

type HomeProps = {
  onCloseSpinner: () => void;
};
export default function Home({ onCloseSpinner }: HomeProps) {
  const [isIntersecting, setIsIntersecting] = useState(false);

  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    onCloseSpinner();
    const observer = new IntersectionObserver(
      ([entry]) => {
        setIsIntersecting(entry.isIntersecting);
      },
      { rootMargin: "-100px" }
    );
    console.log(isIntersecting);
    observer.observe(ref.current!);
    return () => observer.disconnect();
  }, [isIntersecting]);

  useEffect(() => {
    if (isIntersecting) {
      ref.current!.querySelectorAll("div").forEach((div) => {
        div.classList.add(`${styles.slideIn}`);
      });
    } else {
      ref.current!.querySelectorAll("div").forEach((div) => {
        div.classList.remove(`${styles.slideIn}`);
      });
    }
  }, [isIntersecting]);
  return (
    <>
      <Head>
        <title>Home Cook Recipe Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.main}>
        <h1>
          Home Cook Recipe Book <GiNotebook />
        </h1>
        <div className={styles["register-login"]}>
          <a
            className={styles["google-link"]}
            href="http://localhost:8000/google"
          >
            <div>
              <FcGoogle />
            </div>
            Continue with Google
          </a>
        </div>
      </section>
      <div className={styles.features} ref={ref}>
        <div className={styles.left}>left</div>
        <div className={styles.right}>right</div>
      </div>
    </>
  );
}
